// Notes Actions
export const ADD_NEW_NOTE = "ADD_NEW_NOTE";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const REMOVE_NOTE = "REMOVE_NOTE";

// Mural Actions
export const SET_SELECTED_NOTE = "SET_SELECTED_NOTE";
export const PUSH_SELECTED_NOTE = "PUSH_SELECTED_NOTE";
export const REMOVE_SELECTED_NOTE = "REMOVE_SELECTED_NOTE";
export const REMOVE_ALL_SELECTED_NOTES = "REMOVE_ALL_SELECTED_NOTES";
export const ENABLE_MULTIPLE_SELECTION = "ENABLE_MULTIPLE_SELECTION";
export const DISABLE_MULTIPLE_SELECTION = "DISABLE_MULTIPLE_SELECTION";

// Clipboard aActions
export const ADD_TO_CLIPBOARD = "ADD_TO_CLIPBOARD";
export const CLEAR_CLIPBOARD = "CLEAR_CLIPBOARD";
