// Notes Actions
export const NOTE_ADD = "NOTE_ADD";
export const NOTE_UPDATE = "NOTE_UPDATE";
export const NOTE_DELETE = "NOTE_DELETE";

// Mural Actions
export const SELECTED_NOTE_SET = "SELECTED_NOTE_SET";
export const SELECTED_NOTE_PUSH = "SELECTED_NOTE_PUSH";
export const SELECTED_NOTE_DELETE = "SELECTED_NOTE_DELETE";
export const SELECTED_NOTES_CLEAR = "SELECTED_NOTES_CLEAR";
export const MULTIPLE_SELECTION_ENABLE = "MULTIPLE_SELECTION_ENABLE";
export const MULTIPLE_SELECTION_DISABLE = "MULTIPLE_SELECTION_DISABLE";

// Clipboard aActions
export const CLIPBOARD_ADD = "CLIPBOARD_ADD";
export const CLIPBOARD_CLEAR = "CLIPBOARD_CLEAR";
